apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.1
    helm:
      valueFiles:
      - $values/envs/dev/argocd-image-updater/value.yaml
  - repoURL: git@github.com:devopscope/nodejs-express-mysql.git
    targetRevision: main
    ref: values      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
  revisionHistoryLimit: 3