helm:
  parameters:
  - name: image.repository
    value: 529088295441.dkr.ecr.us-east-1.amazonaws.com/ecr-dev-nodejs-app
    forcestring: false
  - name: service.port
    value: "8080"
    forcestring: false
  - name: image.tag
    value: sha-fb72a8adba6603ad2a9f1ab4eb2ce69def99b733
    forcestring: true
  - name: image.name
    value: 529088295441.dkr.ecr.us-east-1.amazonaws.com/ecr-dev-nodejs-app
    forcestring: true
