replicaCount: 1

image:
  repository: your-registry/nodejs-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 128Mi

mysql:
  enabled: false
  host: mysql
  port: 3306
  database: bezkoder
  username: root
  password: password

nodeSelector: {}
tolerations: []
affinity: {} 