apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-for-crossplane
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: creds