{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-app.fullname" . }}-mysql
  labels:
    {{- include "nodejs-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "nodejs-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }} 